pkgs:
  epkgs:
    with epkgs;
    [
      prescient
      ivy-prescient
      company-prescient
      blackout
      geiser
      swift-mode
      esup
      terraform-mode
      osx-trash
      md4rd
      objed
      a
      ace-jump-buffer
      ace-jump-mode
      ace-link
      ace-mc
      ace-window
      adaptive-wrap
      agda2-mode
      aggressive-indent
      alert
      anaphora
      anki-editor
      apache-mode
      apiwrap
      aria2
      #ascii
      #asoc
      async
      auctex
      auctex-latexmk
      auto-compile
      auto-yasnippet
      autothemer
      avy
      avy-menu
      avy-zap
      backup-each-save
      backup-walker
      beacon
      biblio
      bm
      #bookmark-plus
      browse-at-remote
      browse-kill-ring
      #browse-kill-ring-plus
      button-lock
      #bytecomp-simplify
      calfw
      calfw-cal
      calfw-org
      centered-cursor-mode
      change-inner
      chess
      circe
      cl-lib
      clipmon
      cmake-font-lock
      cmake-mode
      #col-highlight
      color-moccur
      #color-theme
      command-log-mode
      company
      company-auctex
      company-cabal
      company-coq
      company-ghc
      company-lsp
      company-math
      company-nixos-options
      company-quickhelp
      company-restclient
      company-statistics
      copy-as-format
      counsel
      counsel-dash
      counsel-gtags
      counsel-osx-app
      counsel-projectile
      counsel-tramp
      #crosshairs
      crux
      csv-mode
      ctable
      #cursor-chg
      dante
      dash
      dash-at-point
      dashboard
      deadgrep
      debbugs
      dedicated
      deferred
      deft
      delight
      dhall-mode
      diff-hl
      diffview
      diminish
      dired-ranger
      dired-toggle
      direnv
      discover
      discover-my-major
      docker
      docker-compose-mode
      docker-tramp
      dockerfile-mode
      #doxymacs
      dumb-jump
      ebdb
      #edit-env
      edit-indirect
      edit-server
      #edit-var
      editorconfig
      el-mock
      el-patch
      elfeed
      elfeed-org
      elisp-depend
      elisp-docstring-mode
      elisp-refs
      elisp-slime-nav
      elmacro
      #emacs-load-time
      emms
      emojify
      engine-mode
      enh-ruby-mode
      ensime
      epc
      epl
      erc-hl-nicks
      erc-image
      erc-scrolltoplace
      erc-terminal-notifier
      erefactor
      eshell-autojump
      eshell-bookmark
      eshell-up
      eshell-z
      esxml
      eval-expr
      eval-in-repl
      evil
      exec-path-from-shell
      expand-region
      eyebrowse
      f
      fancy-narrow
      feebleline
      #fence-edit
      #fetchmail-mode
      filladapt
      flx
      flymake-shellcheck
      flycheck
      flycheck-haskell
      flycheck-hdevtools
      flycheck-package
      fn
      focus
      font-lock-studio
      free-keys
      fringe-helper
      fullframe
      fuzzy
      ggtags
      ghub
      ghub-plus
      ghub-plus
      gist
      git
      git-annex
      git-gutter
      git-link
      git-timemachine
      #git-undo
      gitattributes-mode
      gitconfig-mode
      github-pullrequest
      gitignore-mode
      gitpatch
      gntp
      gnu-apl-mode
      gnus-alias
      #gnus-harvest
      golden-ratio
      google-this
      goto-last-change
      graphviz-dot-mode
      grapnel
      gruvbox-theme
      haskell-mode
      helm
      helm-bibtex
      helm-dash
      helm-descbinds
      helm-describe-modes
      helm-firefox
      helm-google
      helm-navi
      helm-org-rifle
      helpful
      highlight
      #highlight-cl
      highlight-defined
      highlight-numbers
      historian
      #hl-line-plus
      ht
      htmlize
      hydra
      hyperbole
      ialign
      ibuffer-vc
      iedit
      iflipb
      imenu-list
      #indent-shift
      inf-ruby
      #info-lookmore
      initsplit
      ipcalc
      ivy
      ivy-historian
      ivy-hydra
      ivy-pass
      ivy-rich
      ivy-explorer
      ix
      jinja2-mode
      jq-mode
      js2-mode
      js3-mode
      json-mode
      json-reformat
      json-snatcher
      key-chord
      know-your-http-well
      kv
      langtool
      lcr
      ledger-mode
      lentic
      let-alist
      link-hint
      lispy
      list-utils
      log4e
      logito
      loop
      lsp-haskell
      lsp-mode
      lsp-ui
      lua-mode
      m-buffer
      macrostep
      magit
      magit-gh-pulls
      magit-annex
      magit-filenotify
      magit-gitflow
      magit-imerge
      magit-lfs
      magit-popup
      magit-tbdiff
      magit-todos
      magithub
      #makefile-runner
      makey
      malyon
      markdown-mode
      markdown-preview-mode
      marshal
      math-symbol-lists
      mc-extras
      mediawiki
      memory-usage
      #message-x
      mic-paren
      minimap
      modalka
      mmm-mode
      #moccur-edit
      mode-line-bell
      monitor
      #mudel
      multi-term
      multifiles
      multiple-cursors
      muse
      names
      nasm-mode
      navi-mode
      #nf-procmail-mode
      nginx-mode
      nix-buffer
      nix-mode
      nix-sandbox
      nixos-options
      no-littering
      noflet
      nov
      nyan-mode
      oauth2
      ob-diagrams
      ob-restclient
      olivetti
      operate-on-number
      org-bookmark-heading
      org-bullets
      org-context
      org-gcal
      org-journal
      #org-opml
      org-pdfview
      org-plus-contrib
      org-pomodoro
      org-ref
      org-rich-yank
      org-super-agenda
      org-tree-slide
      org-web-tools
      orgit
      orgnav
      orgtbl-aggregate
      origami
      osx-clipboard
      outorg
      outshine
      ov
      #ovpn-mode
      #ox-extra
      ox-hugo
      ox-pandoc
      #ox-texinfo-plus
      package-lint
      packed
      page-break-lines
      pandoc-mode
      paradox
      paredit
      parent-mode
      parsebib
      parsec
      pass
      password-store
      password-store-otp
      auth-source-pass
      pcre2el
      pdf-tools
      #per-window-point
      persistent-scratch
      #peval
      pfuture
      phi-search
      phi-search-mc
      pkg-info
      plantuml-mode
      po-mode
      popup
      #popup-pos-tip
      #popup-ruler
      popwin
      pos-tip
      powerline
      powershell
      #pp-c-l
      prodigy
      projectile
      proof-general
      python-mode
      racer
      rainbow-delimiters
      rainbow-mode
      redshank
      regex-tool
      repl-toggle
      request
      restclient
      reveal-in-osx-finder
      rich-minority
      riscv-mode
      #rs-gnus-summary
      rust-mode
      ryo-modal
      s
      sbt-mode
      scala-mode
      #sdcv-mode
      selected
      seq
      shackle
      shift-number
      shm
      shut-up
      simple-httpd
      #sky-color-clock
      slime
      smart-jump
      smart-mode-line
      smart-newline
      smart-region
      smartparens
      smartscan
      smex
      sort-words
      sos
      spaceline
      spinner
      springboard
      sql-indent
      ssh-config-mode
      steam
      #stopwatch
      string-edit
      string-inflection
      structured-haskell-mode
      super-save
      #supercite
      swiper
      sx
      #tablegen-mode
      tablist
      tagedit
      #tidy
      transpose-mark
      treemacs
      tuareg
      typo
      undo-tree
      use-package
      uuidgen
      vdiff
      vimish-fold
      visual-fill-column
      visual-regexp
      visual-regexp-steroids
      vlf
      #vline
      web
      web-beautify
      web-mode
      web-server
      websocket
      wgrep
      which-key
      whitespace-cleanup-mode
      whole-line-or-region
      window-purpose
      with-editor
      #word-count-mode
      worf
      ws-butler
      x86-lookup
      xml-rpc
      #xray
      yaml-mode
      mu4e-alert
      mu4e-conversation
      slack
      #yaoddmuse
      #yari-with-buttons
      yasnippet
      z3-mode
      zoom
      zoutline
      ztree
      typit
      zzz-to-char
      zygospore
    ]
