pkgs:
  version:
    hpkgs:
      with hpkgs;
      [
        # kmettiverse
        adjunctions
        algebra
        approximate
        base-orphans
        bifunctors
        bits
        bound
        bytes
        compensated
        compressed
        concurrent-supply
        constraints
        contravariant
        discrimination
        distributive
        either
        eq
        exceptions
        free
        gc
        gl
        heaps
        hyperloglog
        hyphenation
        intern
        intervals
        kan-extensions
        lens
        lens-action
        linear
        machines
        perhaps
        pointed
        profunctors
        recursion-schemes
        reducers
        semigroupoids
        tagged
        transformers-compat
        unpacked-containers
        vector-instances
        zippers
        # end kmett
        # effects
        polysemy
        polysemy-plugin
        #polysemy-zoo
        # end effects
        # servant
        servant
        servant-client
        servant-docs
        servant-foreign
        servant-server
        # end servant
        # testagram
        checkers
        hedgehog
        hspec
        hspec-expectations
        hspec-megaparsec
        hspec-wai
        lens-properties
        QuickCheck
        quickcheck-instances
        tasty
        tasty-hedgehog
        tasty-hspec
        tasty-hunit
        tasty-quickcheck
        tasty-th
        # end test
        # AWS
        #amazonka
        #amazonka-ec2
        #amazonka-s3
        #amazonka-cloudwatch
        #amazonka-elbv2
        #amazonka-lambda
        #amazonka-iam
        #amazonka-iam-policy
        #amazonka-route53
        #amazonka-route53-autonaming
        #amazonka-route53-domains
        # end AWS
        # JSON
        aeson
        aeson-pretty
        lens-aeson
        # end JSON
        # lenses
        lens
        lens-action
        lens-datetime
        lens-family
        lens-family-core
        lens-family-th
        fclabels
        # end lenses
        Agda
        Boolean
        ListLike
        Decimal
        amqp
        attoparsec
        barbies
        base
        base-unicode-symbols
        binary
        binary-orphans
        bindings-DSL
        bytestring
        bytestring-mmap
        case-insensitive
        cassava
        cereal
        chronos
        co-log
        comonad
        composition
        connection
        containers
        convertible
        criterion
        cryptonite
        css-text
        curl
        data-checked
        data-default
        data-default-class
        deepseq
        deepseq-generics
        derive-storable
        deriving-compat
        diagrams
        directory
        dlist
        dlist-instances
        dns
        errors
        fgl
        file-embed
        filepath
        fingertree
        fmlist
        foldl
        fsnotify
        generic-lens
        generic-random
        ghc
        groups
        hashable
        hashtables
        haskell-src
        haskell-src-exts
        haskell-src-meta
        hasktags
        hierarchy
        higgledy
        hmatrix
        hslogger
        http-client
        http-client-tls
        http-date
        http-media
        http-types
        insert-ordered-containers
        interpolate
        io-memoize
        language-c
        lattices
        lifted-async
        lifted-base
        linear
        logict
        machines
        managed
        markov-chain
        massiv
        megaparsec
        mmorph
        modern-uri
        optparse-applicative
        optparse-generic
        parallel
        parallel-io
        pipes
        pointed
        prettyprinter
        prettyprinter-ansi-terminal
        primitive
        typed-process
        random-fu
        regex-applicative
        regex-base
        regex-compat
        regex-posix
        regex-tdfa-text
        repline
        req
        rerebase
        retry
        safe
        safe-money
        scientific
        shake
        split
        stm
        stm-chans
        streamly
        tar
        tardis
        template-haskell
        temporary
        text
        text-metrics
        these
        total
        transformers
        transformers-base
        turtle
        unagi-chan
        uniplate
        unix-compat
        unordered-containers
        uuid
        vector
        void
        wreq
        yaml
        zlib
      ]
