pkgs:
  version:
    hpkgs:
      with hpkgs;
      [
        Agda
        Boolean
        HTTP
        HUnit
        IfElse
        ListLike
        MemoTrie
        MissingH
        MonadPrompt
        Decimal
        #Chart
        #Chart-diagrams
        #Network-NineP
        QuickCheck
        ShellCheck
        abstract-deque
        abstract-par
        acid-state
        amazonka
        amazonka-ec2
        amazonka-s3
        amazonka-cloudwatch
        amazonka-elbv2
        amazonka-lambda
        amazonka-iam
        amazonka-iam-policy
        amazonka-route53
        amazonka-route53-autonaming
        amazonka-route53-domains
        adjunctions
        aeson
        aeson-pretty
        alex
        amqp
        async
        async-pool
        attempt
        attoparsec
        base
        base-unicode-symbols
        base16-bytestring
        base64-bytestring
        basic-prelude
        bifunctors
        binary
        binary-orphans
        bindings-DSL
        bool-extras
        bound
        byteable
        byteorder
        bytes
        bytestring
        bytestring-mmap
        bytestring-show
        c2hsc
        cabal-install
        cabal2nix
        case-insensitive
        cassava
        categories
        cereal
        charset
        checkers
        chunked-data
        cmdargs
        comonad
        comonad-transformers
        composition
        compressed
        cond
        configurator
        connection
        constraints
        containers
        contravariant
        convertible
        cpphs
        criterion
        cryptohash
        cryptohash-md5
        cryptohash-sha1
        cryptohash-sha256
        cryptohash-sha512
        cryptonite
        css-text
        curl
        data-checked
        data-default
        data-default-class
        data-fix
        deepseq
        deepseq-generics
        derive-storable
        deriving-compat
        dhall
        diagrams
        directory
        distributive
        dlist
        dlist-instances
        dns
        doctest
        either
        errors
        exceptions
        extensible-exceptions
        failure
        fast-logger
        fclabels
        fgl
        file-embed
        filemanip
        filepath
        fingertree
        fmlist
        foldl
        free
        free-vl
        freer-simple
        fsnotify
        generic-lens
        generic-random
        ghc
        ghc-core
        ghc-paths
        groupoids
        groups
        hamlet
        happy
        hashable
        hashing
        hashtables
        haskell-lexer
        haskell-src
        haskell-src-exts
        haskell-src-meta
        hasktags
        hedgehog
        here
        hierarchy
        hlibgit2
        hlint
        hmatrix
        #hnix
        hslogger
        hspec
        hspec-expectations
        hspec-megaparsec
        hspec-wai
        html
        http-client
        http-client-tls
        http-date
        http-media
        http-types
        insert-ordered-containers
        interpolate
        io-memoize
        io-storage
        io-streams
        json
        json-stream
        kan-extensions
        kdt
        keys
        language-c
        lattices
        lens
        lens-action
        lens-aeson
        lens-datetime
        lens-family
        lens-family-core
        lens-family-th
        lifted-async
        lifted-base
        linear
        list-extras
        list-t
        logging
        logict
        machinecell
        machines
        markov-chain
        megaparsec
        mmorph
        modern-uri
        monad-control
        monad-coroutine
        monad-extras
        monad-logger
        monad-loops
        monad-par
        monad-par-extras
        monad-parallel
        monad-stm
        monadlist
        monadloc
        mono-traversable
        monoid-extras
        mtl
        multimap
        nats
        network
        network-simple
        newtype
        numbers
        operational
        optparse-applicative
        optparse-generic
        parallel
        parallel-io
        parsec
        parsers
        pcre-heavy
        pipes
        pipes-async
        pipes-attoparsec
        pipes-binary
        pipes-bytestring
        pipes-concurrency
        pipes-extras
        pipes-group
        pipes-http
        pipes-network
        pipes-parse
        pipes-safe
        pipes-text
        pipes-zlib
        pointed
        pointfree
        pointful
        polysemy
        polysemy-plugin
        posix-paths
        pretty-show
        pretty-simple
        prettyprinter
        prettyprinter-ansi-terminal
        primitive
        process
        process-extras
        profunctors
        quickcheck-instances
        random
        random-fu
        random-source
        recursion-schemes
        recursors
        reducers
        reflection
        regex-applicative
        regex-base
        regex-compat
        regex-posix
        regex-tdfa-text
        repline
        req
        rerebase
        resourcet
        retry
        safe
        safecopy
        scientific
        semigroupoids
        semigroups
        semiring-simple
        serialise
        servant
        servant-client
        servant-docs
        servant-foreign
        servant-server
        shake
        shakespeare
        silently
        simple-reflect
        speculation
        split
        spoon
        stm
        stm-chans
        #stm-stats
        streamly
        strict
        stringsearch
        strptime
        structured-haskell-mode
        stylish-haskell
        styx
        syb
        system-fileio
        system-filepath
        tagged
        tar
        tardis
        tasty
        tasty-hedgehog
        tasty-hspec
        tasty-hunit
        tasty-quickcheck
        tasty-th
        template-haskell
        temporary
        text
        text-metrics
        text-show
        these
        thyme
        time
        time-recurrence
        #timeparsers
        tls
        total
        transformers
        transformers-base
        turtle
        uniplate
        unix-compat
        unordered-containers
        unpacked-containers
        uuid
        vector
        void
        wreq
        xeno
        xml
        xmlbf
        xmlbf-xeno
        yaml
        zippers
        zlib
      ]
